Re-write file location cache
Ionian-Web3-Storage/ionian-rust pull request #58
Opened 2022-08-05 08:10 UTC by qhz-ty

1. Change crate name to `file_location_cache` to distinguish with the `gossip_cache` in `network` crate.
2. Garbage collect file announcements based on the origin `timestamp` in `SignedAnnounceFile` message.
3. Limit the total number of announcements instead of total files.

2022-08-07 15:41 UTC, loganionion requested changes

2022-08-07 15:41 UTC, loganionion commented on node/router/src/service.rs
> +    gossip_cache: Arc<FileLocationCache>,
better to rename gossip_cache to file_location_cache?

2022-08-07 15:41 UTC, loganionion commented on node/router/src/service.rs
> +        gossip_cache: Arc<FileLocationCache>,
same as above

2022-08-07 15:41 UTC, loganionion commented on node/src/client/builder.rs
> +    gossip_cache: Option<Arc<FileLocationCache>>,
rename

2022-08-07 15:41 UTC, loganionion commented on node/sync/src/controllers/serial.rs
> +    gossip_cache: Arc<FileLocationCache>,
rename

2022-08-07 15:41 UTC, loganionion commented on node/sync/src/controllers/serial.rs
> +        gossip_cache: Arc<FileLocationCache>,
rename

2022-08-07 15:41 UTC, loganionion commented on node/sync/src/controllers/serial.rs
> +        gossip_cache: Arc<FileLocationCache>,
rename

2022-08-07 15:41 UTC, loganionion commented on node/sync/src/service.rs
> +    gossip_cache: Arc<FileLocationCache>,
rename

2022-08-07 15:41 UTC, loganionion commented on node/sync/src/service.rs
> +        gossip_cache: Arc<FileLocationCache>,
rename

2022-08-08 02:44 UTC, qhz-ty reviewed
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @ionian-dev, @loganionion, and @zz-ionian)

___
*[`node/router/src/service.rs` line 70 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58#-N8h2g2ZWNodOEKU__AN-r1-70:-N8vKXGHC_S9k6VrScJJ:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/0dd9017b865e5507d02a8669ca40e29a1a136c38/node/router/src/service.rs#L70)):*
<details><summary><i>Previously, loganionion wrote…</i></summary><blockquote>

better to rename gossip_cache to file_location_cache?
</blockquote></details>

Done.
___
*[`node/router/src/service.rs` line 87 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58#-N8h2g2ZWNodOEKU__AN-r1-87:-N8vKYtx7Ta6ypsaZRQJ:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/0dd9017b865e5507d02a8669ca40e29a1a136c38/node/router/src/service.rs#L87)):*
<details><summary><i>Previously, loganionion wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`node/src/client/builder.rs` line 57 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58#-N8h2g2_XzRuhWfrLDKe-r1-57:-N8vK_UB9AgyY6F5lQDn:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/0dd9017b865e5507d02a8669ca40e29a1a136c38/node/src/client/builder.rs#L57)):*
<details><summary><i>Previously, loganionion wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`node/sync/src/service.rs` line 83 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58#-N8h2g2_XzRuhWfrLDKi-r1-83:-N8vKbcj6FJ7SF0Ix9YK:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/0dd9017b865e5507d02a8669ca40e29a1a136c38/node/sync/src/service.rs#L83)):*
<details><summary><i>Previously, loganionion wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`node/sync/src/service.rs` line 98 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58#-N8h2g2_XzRuhWfrLDKi-r1-98:-N8vKcCi9ssci5wwiskw:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/0dd9017b865e5507d02a8669ca40e29a1a136c38/node/sync/src/service.rs#L98)):*
<details><summary><i>Previously, loganionion wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`node/sync/src/controllers/serial.rs` line 196 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58#-N8h2g2_XzRuhWfrLDKg-r1-196:-N8vKd0X3jHHclfetmhL:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/0dd9017b865e5507d02a8669ca40e29a1a136c38/node/sync/src/controllers/serial.rs#L196)):*
<details><summary><i>Previously, loganionion wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`node/sync/src/controllers/serial.rs` line 206 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58#-N8h2g2_XzRuhWfrLDKg-r1-206:-N8vKesL6_uNAXF1Bc_3:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/0dd9017b865e5507d02a8669ca40e29a1a136c38/node/sync/src/controllers/serial.rs#L206)):*
<details><summary><i>Previously, loganionion wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`node/sync/src/controllers/serial.rs` line 227 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58#-N8h2g2_XzRuhWfrLDKg-r1-227:-N8vKfOP83FzAVHAfDit:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/0dd9017b865e5507d02a8669ca40e29a1a136c38/node/sync/src/controllers/serial.rs#L227)):*
<details><summary><i>Previously, loganionion wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-08 02:55 UTC, loganionion approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 13 of 17 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/58#-:-N8vNBAD5EsLpQcp4ewn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ionian-dev and @zz-ionian)



<!-- Sent from Reviewable.io -->

2022-08-08 03:43 UTC, merged